version: '3.8'

services:
    
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    deploy:
      replicas: 4
    restart: always
    environment:
      - PING_LISTEN_PORT
    networks:
      - front-network
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on: 
      - my_app
    networks:
      - front-network
networks:
  front-network:
    driver: bridge
volumes:
  db_data:
